operations:
  debit:
    bonus: 0.5
  withdraw:
    tax: 1.0

spring:
  application:
    name: fortnight
  datasource:
    password: "0123456789"
    username: "root"
    url: jdbc:mysql://localhost:3306/fortnight
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
